3 runs

diff --git a/.github/workflows/matrix.yml b/.github/workflows/matrix.yml
--- a/.github/workflows/matrix.yml
+++ b/.github/workflows/matrix.yml
@@ -12,22 +12,28 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        matrix-value: [3, 6]
+        matrix-value: [1, 2, 3]
     name: Sleep ${{ matrix.matrix-value }}s
     steps:
       - name: Sleep for matrix value
         run: |
           # if the matrix value is 20, simulate a failure
-          # if [ ${{ matrix.matrix-value }} -eq 20 ]; then
-          #   echo "Simulating failure for matrix value 20"
+          if [ "$GITHUB_RUN_ATTEMPT" -eq 1 ]; then
+            if [ ${{ matrix.matrix-value }} -eq 1 ]; then
+              echo "Simulating failure for matrix value 1"
+              exit 1
+            fi
+            if [ ${{ matrix.matrix-value }} -eq 2 ]; then
+              echo "Simulating failure for matrix value 2"
+              exit 1
+            fi
+          fi
+          # if [ "$GITHUB_RUN_ATTEMPT" -gt 1 ]; then
+          #   echo "🔁 This is a re-run (attempt $GITHUB_RUN_ATTEMPT)"
+          # else
+          #   echo "▶️ This is the first run"
           #   exit 1
           # fi
-          if [ "$GITHUB_RUN_ATTEMPT" -gt 1 ]; then
-            echo "🔁 This is a re-run (attempt $GITHUB_RUN_ATTEMPT)"
-          else
-            echo "▶️ This is the first run"
-            exit 1
-          fi
           sleep ${{ matrix.matrix-value }}
 
   matrix_aggregate:
